name: Test Trigger

on:
  workflow_dispatch:
  push:
    paths:
      - 'test_trigger.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        run: |
          echo "✅ GitHub Actions is working!"
          echo "Current time: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}" 